-- MySQL Script generated by MySQL Workbench
-- Thu Aug  8 16:12:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DentistPatient
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DentistPatient
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DentistPatient` DEFAULT CHARACTER SET utf8 ;
USE `DentistPatient` ;

-- -----------------------------------------------------
-- Table `DentistPatient`.`Dentist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DentistPatient`.`Dentist` ;

CREATE TABLE IF NOT EXISTS `DentistPatient`.`Dentist` (
  `DentistId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(25) NOT NULL,
  `Specialty` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DentistId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentistPatient`.`Patient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DentistPatient`.`Patient` ;

CREATE TABLE IF NOT EXISTS `DentistPatient`.`Patient` (
  `PatientId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(60) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(25) NOT NULL,
  `Priority` VARCHAR(45) NOT NULL,
  `Notes` VARCHAR(45) NULL,
  `DentistId` INT NOT NULL,
  PRIMARY KEY (`PatientId`),
  INDEX `fk_Patient_Dentist_idx` (`DentistId` ASC) VISIBLE,
  CONSTRAINT `fk_Patient_Dentist`
    FOREIGN KEY (`DentistId`)
    REFERENCES `DentistPatient`.`Dentist` (`DentistId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DentistPatient`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DentistPatient`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `DentistPatient`.`Appointment` (
  `AppointmentId` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Time` TIME NOT NULL,
  `Location` VARCHAR(100) NOT NULL,
  `Reason` VARCHAR(300) NOT NULL,
  `DentistId` INT NOT NULL,
  `PatientId` INT NOT NULL,
  PRIMARY KEY (`AppointmentId`),
  INDEX `fk_Appointment_Dentist1_idx` (`DentistId` ASC) VISIBLE,
  INDEX `fk_Appointment_Patient1_idx` (`PatientId` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Dentist1`
    FOREIGN KEY (`DentistId`)
    REFERENCES `DentistPatient`.`Dentist` (`DentistId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Appointment_Patient1`
    FOREIGN KEY (`PatientId`)
    REFERENCES `DentistPatient`.`Patient` (`PatientId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
